### ISSUE TITLE
"Bogus userid" error if identd is turned off and nothing to slow it down

### ISSUE THREAD

**Issue by hiddn** [UndernetIRC/ircu2#1]
The following all happens quickly without any delay, and without any time for the client to send any nick/user data:

$ telnet 127.0.0.1 6666
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
NOTICE AUTH :*** Checking Ident
NOTICE AUTH :*** No ident response
ERROR :Closing Link:  by hidden.undernet.org (USER: Bogus userid.)
Connection closed by foreign host.

Then, after typing the following command, it connects without a problem:

$ sudo iptables -I INPUT -i lo -m tcp -p tcp --dport 113 -j DROP
$ telnet 127.0.0.1 6666
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
NOTICE AUTH :*** Checking Ident
[...]

Connection works fine if identd is working on the client, so it just doesn't work when it gets a quick connection refused on port 113.

**Comment by entrope** [comment]
Fixed in commit dc983eff145c2f5c8257fa671800cd1b4374c4e2.
