### ISSUE TITLE
WebSockets Support

### ISSUE THREAD

**Issue by zoltyvigo** [UndernetIRC/ircu2#11]
With the popularity of KiwiIRC using the new Websockets standard, I see a need for it to be implemented on the IRCD.

It can be based on Unreal support.
https://github.com/unrealircd/unrealircd/blob/unreal50/src/modules/websocket.c

**Comment by entrope** [comment]
ircu2 already includes support for a web interface (WEBIRC), without the drawback that the web server needs to also run an IRC server, or requiring a reverse proxy in front of the web and IRC servers.
