### ISSUE TITLE
`MODE #chan +k :` returns ERR_NEEDMOREPARAMS instead of ERR_INVALIDMODEPARAM

### ISSUE THREAD

**Issue by progval** [UndernetIRC/ircu2#13]
Hi,

I just noticed this when setting an empty channel key:

```
C -> S: MODE #chan +k :
S -> C: :My.Little.Server 461 foo MODE +k :Not enough parameters
```

`:` should be parsed as an empty parameter (as per the usual IRC syntax), not a lack of parameter.

So the response should probably be ERR_INVALIDKEY, like other invalid keys.

By the way, we are trying to [converge toward a new numeric, ERR_INVALIDMODEPARAM](https://github.com/ircdocs/modern-irc/pull/111). So instead, it could be this:

```
:My.Little.Server 696 foo #chan k * :Channel keys cannot be empty
```

(and adapt the error message for other types of invalid keys)

**Comment by entrope** [comment]
This case has always been reported with ERR_NEEDMOREPARAMS.  ERR_INVALIDKEY was added later to handle the cases of invalid (but existing) keys.
