### ISSUE TITLE
incomplete STATUSMSG= support

### ISSUE THREAD

**Issue by maroonbells** [UndernetIRC/ircu2#28]
* /notice +#channel message is not supported, as promised by STATUSMSG=@+
* STATUSMSG is also not being supported at all for PRIVMSG, also promised by the same

The 005 message contains STATUSMSG=@+ which indicates that @#channel is a valid target for sending to all channel @ops-and-higher (which there are none higher), and that +#channel is a valid target for sending a notice to all voice-and-higher, which for Undernet means voice+halfops+ops

/notice @#channel message
/notice +#channel message

While 1st example works, the 2nd one does not. I vote for enabling +#channel rather than editing the + out of STATUSMSG=.

Also, I don't recall ever seeing a network where the targets in STATUSMSG= do not match the same group of PREFIX= levels, whatever they are, so I imagine there are channels which would find it useful to be able to have group notice to all

*	*

Also, it's standard for the STATUSMSG to work for *all* messages, not just notice.
However Undernet is not supporting STATUSMSG for ANY of the various PRIVMSG usage, i.e. the mIRC equivalent of:

/msg @#channel message
/describe @#channel message
/ctcp @#channel message

I tested these in a test channel without any modes set, so they were not being blocked by any settings that I'm aware of.

**Comment by entrope** [comment]
This is working as intended.  +WHATEVER is an opless channel.  WALLCHOPS and WALLVOICES send to channel operators and voiced users, with PRIVMSG @#channel and NOTICE @#channel as convenience syntax.

I don't know what /describe is supposed to do, but CTCP is translated by the client to a PRIVMSG or NOTICE with special syntax.  ircu is not responsible for how your client interprets those commands.

**Comment by maroonbells** [comment]
It's not working according to the standard IRC protocol. I've never seen '+' being used as a special form of channelname, and "/quote JOIN +test" does not work. If there is a channelname beginning with '+' that conflicts with the CHANTYPES=#& token.

The STATUSMSG= token indicates a list of prefix modes that work with both the PRIVMSG and NOTICE commands, and STATUSMSG=@+ is informing the client that all 4 of these combos work:

/quote NOTICE @#channel :notice to all ops
/quote NOTICE +#channel :notice to all voices
/quote PRIVMSG @#channel :notice to all ops
/quote PRIVMSG +#channel :notice to all voices

However only the 1st of 4 promised syntaxes works. So if the +#channel target does conflict with some other network setting, I guess the '+' would need to be edited out of the STATUSMSG= token.

My mention of the DESCRIBE and CTCP was just restating about the PRIVMSG forms that were not working as advertized by STATUSMSG=, and DESCRIBE is just the CTCP ACTION that's commonly used as /me message.

I do see that WALLCHOPS and WALLVOICES messages are received as notices, however they are not the equivalent behavior of STATUSMSG, in several ways:

* WALLCHOPS and WALLVOICES insert a '@' or '+' in front of the message you send, which the above 4 syntax do not do.
* the above 4 STATUSMSG= formats are supposed to be visible to the indicated status level *AND ABOVE*, which means that messages sent to STATUSMSG= target +#channel should also be visible to all %halfop and @ops too, but WALLVOICES messages are seen only by the voices.
* The WALLVOICES message arrives using the wrong target:
	NOTICE @#channel :+ test
 ... while using the STATUSMSG= target form +#channel normally arrives as
 	NOTICE +#channel :test

**Comment by maroonbells** [comment]
looks like I accidentally closed it with my reply, not sure how to reopen it
