### ISSUE TITLE
Hello this possible add the spam

### ISSUE THREAD

**Issue by darksis** [UndernetIRC/ircu2#4]
Hello i see in ircu2 a some modules like this
SPAM_OPER_COUNTDOWN
 * Type: integer
 * Default: 5

Number of times a user may continue to join in a spambot-like fashion
between snotices.

SPAM_EXPIRE_TIME
 * Type: integer
 * Default: 120

Number of seconds before a spambot-like join is "forgotten".

SPAM_JOINED_TIME
 * Type: integer
 * Default: 60

Number of seconds a client must stay in channels before a join/part
sequence is not considered spambot-like.  This can be set to zero to
disable spambot warnings.

SPAM_FJP_COUNT
 * Type: integer
 * Default: 5

Number of fast join-part sequences before a client is judged to look
like a spambot.
and my question if this possible inside them to a new version

**Comment by entrope** [comment]
That code is very old, and not very well-suited to detecting or stopping the typical abuse patterns that Undernet sees, so we do not envision merging it into the main code base.  We are examining other ways to protect users and channels from drones and spambots.
