### ISSUE TITLE
IRCv3 Support

### ISSUE THREAD

**Issue by zoltyvigo** [UndernetIRC/ircu2#8]
I think it's time for UndernetIRC (ircu) to start supporting IRCv3.

The list of supported extensions are:

- [cap-notify](https://ircv3.net/specs/core/capability-negotiation#cap-notify)
- [account-notify](https://ircv3.net/specs/extensions/account-notify-3.1)
- [account-tag](https://ircv3.net/specs/extensions/account-tag-3.2)
- [away-notify](https://ircv3.net/specs/extensions/away-notify-3.1)
- [batch](https://ircv3.net/specs/extensions/batch-3.2)
- [chghost](https://ircv3.net/specs/extensions/chghost-3.2)
- [echo-message](https://ircv3.net/specs/extensions/echo-message-3.2)
- [extended-join](https://ircv3.net/specs/extensions/extended-join-3.1)
- [invite-notify](https://ircv3.net/specs/extensions/invite-notify-3.2)
- [message-tags](https://ircv3.net/specs/extensions/message-tags)
- [Monitor](https://ircv3.net/specs/core/monitor-3.2)
- [msgid](https://ircv3.net/specs/extensions/message-ids)
- [multi-prefix](https://ircv3.net/specs/extensions/multi-prefix-3.1)
- [SASL v3.1](https://ircv3.net/specs/extensions/sasl-3.1)
- [SASL v3.2](https://ircv3.net/specs/extensions/sasl-3.2)
- [server-time](https://ircv3.net/specs/extensions/server-time-3.2)
- [sts](https://ircv3.net/specs/extensions/sts)
- [userhost-in-names](https://ircv3.net/specs/extensions/userhost-in-names-3.2)

The extensions would be activatable-deactivatable using f-lines (Features block).

If Undernet is interested in support, I could contribute some of the features, such as account-notify, away-notify, extended-join, multi-prefix, userhost-in-names and Monitor.

**Comment by entrope** [comment]
If you want to propose specific extensions, do so in individual feature requests.

The last time I looked at IRCv3 proposals, they were a terrible mess, and a quick look does not suggest that has changed significantly.

And not to be too blunt about it, but I do not think there is any reason we should care what time you think it is.  That was a terribly unconvincing lead-in to a feature request.
